# Generated by Django 6.0.7 on 2026-07-18 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupdocument_documentchunk'),
        ('meetings', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('category', models.CharField(choices=[('fact', 'fact'), ('goal', 'goal'), ('requirement', 'requirement'), ('decision', 'decision'), ('preference', 'preference'), ('constraint', 'constraint'), ('responsibility', 'responsibility'), ('client_expectation', 'client_expectation'), ('technical', 'technical'), ('process', 'process'), ('risk', 'risk'), ('historical', 'historical'), ('deadline', 'deadline'), ('scope', 'scope'), ('terminology', 'terminology')], max_length=32)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('temporary', 'Temporary'), ('disputed', 'Disputed'), ('outdated', 'Outdated'), ('superseded', 'Superseded'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='approved', max_length=16)),
                ('citations', models.JSONField(default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_provider', models.CharField(blank=True, max_length=32)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='groups.group')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='meetings.meeting')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='memory.groupmemory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorySuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('category', models.CharField(choices=[('fact', 'fact'), ('goal', 'goal'), ('requirement', 'requirement'), ('decision', 'decision'), ('preference', 'preference'), ('constraint', 'constraint'), ('responsibility', 'responsibility'), ('client_expectation', 'client_expectation'), ('technical', 'technical'), ('process', 'process'), ('risk', 'risk'), ('historical', 'historical'), ('deadline', 'deadline'), ('scope', 'scope'), ('terminology', 'terminology')], max_length=32)),
                ('citations', models.JSONField(default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('conflict_candidates', models.JSONField(default=list)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('temporary', 'Temporary'), ('merged', 'Merged'), ('replaced', 'Replaced')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_suggestions', to='groups.group')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_suggestions', to='meetings.meeting')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_suggestions', to='memory.groupmemory')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolution_action', models.CharField(blank=True, choices=[('keep_existing', 'Keep Existing'), ('replace_existing', 'Replace Existing'), ('keep_both', 'Keep Both')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('existing_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='memory.groupmemory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_conflicts', to='groups.group')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='memory.memorysuggestion')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('existing_memory', 'suggestion'), name='uniq_memory_conflict_pair')],
            },
        ),
        migrations.CreateModel(
            name='MemoryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('statement', models.TextField()),
                ('category', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='memory.groupmemory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.workspace')),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('memory', 'version'), name='uniq_memory_version')],
            },
        ),
    ]
